### ISSUE TITLE
Improve etcd dashboard

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/performance-dashboards#2]
The current etcd dashboard based in jsonnet is missing lot of information.
I've seen that @tkashem has done a nice dashboard at https://github.com/tkashem/dittybopper/blob/dashboard/dashboards/etcd-overview.json
We can use it as a starting point.

**Comment by smalleni** [comment]
@jaredoconnell Can you please pick this issue up? This is based on the jsonnet work we were talking about.
